services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    #depends_on:
      #- db

  npbot:
    build: ./bot
    env_file: ./bot/.env
    volumes:
      - ./bot:/app
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: guildmanager-frontend
    ports:
      - "3000:80"   # außen:3000 → container:80 (nginx)
    restart: unless-stopped


  db:
    image: postgres
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
